### ISSUE TITLE
Incorrect behaviour for on receiving a message with reply_markup & selective=true

### ISSUE THREAD

**Issue by m1kola** [overtake/TelegramSwift#379]
The issue https://github.com/overtake/TelegramSwift/issues/52 I reported in December 2017 got closed without explanation a month ago, but I can still reproduce it. 

I checked and can confirm that when a bot sends a message with [`ReplyKeyboardMarkup`](https://core.telegram.org/bots/api#replykeyboardmarkup), [`ReplyKeyboardRemove`](https://core.telegram.org/bots/api#replykeyboardremove) or [`ForceReply`](https://core.telegram.org/bots/api#forcereply) mentioning a user and setting `selective` to `true` the MacOS client behaves differently to iOS clients and to what described in the documentation for these reply markups.

**Comment by overtake** [comment]
can you give a bot with the example?

**Comment by m1kola** [comment]
@overtake sure. In #52 I mentioned [PollBot](https://t.me/PollBot). Also here is a simplified version of my Go bot using [the `github.com/go-telegram-bot-api/telegram-bot-api` package](github.com/go-telegram-bot-api/telegram-bot-api) (tested with version `v4.6.4` of the package, requires a webhook):

```go
package main

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"os"

	tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api"
)

func run(ctx context.Context, log *log.Logger) error {
	apiToken := os.Getenv("TELEGRAM_API_TOKEN")
	tlsCertPath := os.Getenv("TELEGRAM_TLS_CERT_PATH")
	tlsKeyPath := os.Getenv("TELEGRAM_TLS_KEY_PATH")
	webhookPort := os.Getenv("TELEGRAM_WEBHOOK_PORT")

	bot, err := tgbotapi.NewBotAPI(apiToken)
	if err != nil {
		return err
	}

	go func() {
		updates := bot.ListenForWebhook(fmt.Sprintf("/%s/webhook", bot.Token))

		for update := range updates {
			if update.Message != nil {
				switch cmd := update.Message.Command(); cmd {
				case "test":
					test(bot, &update)
				default:
					if update.Message != nil {
						log.Printf("Received a non-command message: %#v\n", update.Message.Text)
					} else {
						log.Println("Received a non-command update:")
					}
				}
				continue
			}
		}
	}()

	addr := fmt.Sprintf(":%s", webhookPort)
	log.Printf("Waiting for updates on %s\n", addr)
	return http.ListenAndServeTLS(addr, tlsCertPath, tlsKeyPath, nil)
}

func test(bot *tgbotapi.BotAPI, update *tgbotapi.Update) error {
	from := update.Message.From
	text := fmt.Sprintf("Hey, [%s](tg://user?id=%d)", from.FirstName, from.ID)

	_, err := bot.Send(
		tgbotapi.MessageConfig{
			BaseChat: tgbotapi.BaseChat{
				ChatID: update.Message.Chat.ID,
				ReplyMarkup: tgbotapi.ReplyKeyboardMarkup{
					ResizeKeyboard: true,
					Keyboard: [][]tgbotapi.KeyboardButton{{
						tgbotapi.NewKeyboardButton("Add item"),
						tgbotapi.NewKeyboardButton("Delete item"),
					}},
					OneTimeKeyboard: true,
					Selective:       true,
				},
			},
			Text:      text,
			ParseMode: tgbotapi.ModeMarkdown,
		},
	)
	return err
}

func main() {
	log := log.New(os.Stdout, "", log.LstdFlags|log.LUTC|log.Lshortfile)

	if err := run(context.Background(), log); err != nil {
		log.Fatal(err)
	}
}

```

This is exactly how I reproduce it, but there are probably other ways (eg. change the device you send a command from):

1. Create a new group with 2 different human users (let's call them User 1 and User 2)
1. Add the [PollBot](https://t.me/PollBot)\your own test bot using the code sample above.
1. For both User 1 and User 2, open Telegram clients on MacOS 
1. For both User 1 and User 2, open Telegram clients on a mobile device (I tested on iOS, but I guess Android can also do)
3. On a mobile device, as a User 1, send the `/newpoll` (for `PollBot`) or `/test` (for the test bot) command

**Result:**

* Bot sends a message mentioning User 1.
* Force reply (for [PollBot](https://t.me/PollBot) or custom keyboard (for the test bot) will appear on:
  * Mobile device for the User 1
  * On MacOS client for the User 1
  * On MacOS client for the User 2


**Expected result:**

* Bot sends a message mentioning User 1.
* Force reply / custom keyboard appears on:
  * Mobile device for the User 1
  * On MacOS client for the User 1

User 2 doesn't see the force reply or a custom keyboard because the message contains `selective=true` on `reply_markup`.

**Comment by overtake** [comment]
Ok. Finally, i have fixed it. Thanks

**Comment by pietrocolombo** [comment]
I noticed that the problem is still there

6.0 (196005) AppStore

**Comment by m1kola** [comment]
Same for me.

@overtake I did not manage to find a relevant PR\commit. Could you please double check that the fix got merged?

**Comment by mayhems1** [comment]
The same issue (((

9.0.1.237033 AppStore
