### ISSUE TITLE
Change menu bar icon color 

### ISSUE THREAD

**Issue by antonlukin** [overtake/TelegramSwift#542]
The icon color changes only when the color scheme is changed, but in the new macOS (Big Sur), menu bar is transparent and the icon is invisible on dark wallpapers with a light theme.

macOS 11.0.1

<img width="224" alt="Снимок экрана 2020-11-15 в 14 24 26" src="https://user-images.githubusercontent.com/454185/99183583-01704780-274e-11eb-8ac7-44fd4fb872b1.png">

<img width="224" alt="Снимок экрана 2020-11-15 в 14 24 26" src="https://user-images.githubusercontent.com/454185/99183654-6deb4680-274e-11eb-9b26-f4fd0bda85bb.png">

**Comment by Lweek** [comment]
Use Control colours for tinting icon instead of standard colours.
https://developer.apple.com/documentation/appkit/nscolor/ui_element_colors

**Comment by antonlukin** [comment]
It seems fixed in 7.2.4 (209524) Stable

**Comment by Lweek** [comment]
You should reopen this issue because it is not solved. 
<img width="345" alt="Screenshot 2020-11-29 at 21 57 53" src="https://user-images.githubusercontent.com/711930/100553363-f2c97a80-328d-11eb-83dd-22eda20a3a46.png">

**Comment by Lweek** [comment]
Color of the icon is based on wallpaper not a dark mode.

**Comment by giorgiopagnoni** [comment]
> @antonlukin You should reopen this issue because it is not solved.
> <img alt="Screenshot 2020-11-29 at 21 57 53" width="345" src="https://user-images.githubusercontent.com/711930/100553363-f2c97a80-328d-11eb-83dd-22eda20a3a46.png">

my icon is also white instead of black in version 7.2.4

**Comment by bawva** [comment]
This issue still remains after 6 months, pretty sure this is a small fix.

**Comment by vivaanmathur** [comment]
https://bugs.telegram.org/c/8440
