### ISSUE TITLE
Notification sound in Do Not Disturb mode

### ISSUE THREAD

**Issue by gerasimvol** [overtake/TelegramSwift#675]
Why app makes sound when DND mode is on? It shouldn't

**Comment by AlwxSin** [comment]
Same here. `8.1.4 (222346) Stable`
It's very disturbing.

**Comment by josser** [comment]
Even if I disable sound for notifications in system settings 
![](https://i.imgur.com/bcVDD04.png)

and set 'Tone' to 'None' in app: 
![](https://i.imgur.com/AmAVbBv.png)

There is still sound of notification and there is not way top change volume.

**Comment by ewqqx** [comment]
This should be fixed, very annoying. I have to quit telegram during meetings etc.

**Comment by Finegorko** [comment]
@overtake please pay attention to this

**Comment by muendelezaji** [comment]
This is still a problem in Telegram (v8.5.226936 Stable) on macOS Monterey. The notification sound is played even when 
(A) Focus/DND mode is on, and (B) sound is disabled in Notification Centre.

![image](https://user-images.githubusercontent.com/1127221/156051576-89f0f855-8cad-4a6e-9df6-b6899b661944.png)

The only way around it was to silence it in the app as mentioned in an earlier post, which is not ideal as sometimes you do want the sound notifications enabled.

**Comment by eboddington** [comment]
Duplicate of https://github.com/overtake/TelegramSwift/issues/767?

**Comment by impulse200** [comment]
Still no progress on this very annoying issue? And no response from devs. Telegram ought to honor different Focus modes.
