### ISSUE TITLE
Telegram does not show in Alt-Tab on macOS Ventura

### ISSUE THREAD

**Issue by pasquale95** [overtake/TelegramSwift#870]
### Steps to reproduce

1. Open Telegram on macOS;
2. Click Alt+Tab to switch to another application;
3. Click Alt+Tab again to switch back to Telegram;
4. Telegram does not show among the opened apps.

For more info please look at https://github.com/lwouis/alt-tab-macos/issues/2092. There's a detailed debugging section where they explain the issue of Telegram Desktop on macOS in details.

### Expected behaviour

Telegram should show among the opened applications.

### Actual behaviour

Telegram does not show among the opened applications.

![image](https://user-images.githubusercontent.com/26608445/200782404-aee2cba4-4c25-4617-9f08-45229fa56cd1.png)

### Operating system

macOS Ventura 13.0

### Version of Telegram Desktop

9.1.1.238861

### Installation source

Static binary from official website

**Comment by elgirafo** [comment]
hopefully, it is an easy fix, it would be really helpful to solve this for the altTab community and users.

**Comment by GHopperMSK** [comment]
Maybe this is why my laptop goes sleep during telegram video calls on MacOS

**Comment by tkeith** [comment]
This issue also affects https://contexts.co/ -- Telegram is no longer showing in the window switcher or app switcher.

**Comment by stingusss** [comment]
Hello. I experience such problem as well and I suffer from this so much. Hope it gets fixed.

**Comment by tibik** [comment]
upvote

**Comment by ramirofages** [comment]
According to another post in other repo, telegram is also not showing up in the XCode Accesibility inspector which may affect other applications:
https://github.com/lwouis/alt-tab-macos/issues/2092#issuecomment-1307769225

**Comment by dwjorgeb** [comment]
having the same issue, had to downgrade to v9.0.1 in order for it to work correctly again

**Comment by arianoangelo** [comment]
Have the same issue here.

**Comment by danil0110** [comment]
Same issue here, very annoying!

**Comment by overtake** [comment]
Fixed in beta

**Comment by stingusss** [comment]
Just tried out the beta (Version 9.1 (239780) Nov 18, 2022 at 21:11) and the problem is fixed! Thank you!

**Comment by jamesdh** [comment]
> This issue also affects https://contexts.co/ -- Telegram is no longer showing in the window switcher or app switcher.

Similarly, this also breaks the ability of [Stay](https://cordlessdog.com/stay/) to reposition Telegram. 

When tinkering with this in Contexts, Telegram appears as an "Apps without windows". So it seems macOS is unable to detect the window for some reason.

**Comment by change-agent** [comment]
This issue still occurred in the latest version of the Mac App Store build ("9.4"), but downloading the website build (9.4.243050 Stable) fixed it for me.
